<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $subject
 * @property clob $body
 * @property integer $recipient_id
 * @property sfGuardUser $recipient
 * 
 * @method string      getSubject()      Returns the current record's "subject" value
 * @method clob        getBody()         Returns the current record's "body" value
 * @method integer     getRecipientId()  Returns the current record's "recipient_id" value
 * @method sfGuardUser getRecipient()    Returns the current record's "recipient" value
 * @method Message     setSubject()      Sets the current record's "subject" value
 * @method Message     setBody()         Sets the current record's "body" value
 * @method Message     setRecipientId()  Sets the current record's "recipient_id" value
 * @method Message     setRecipient()    Sets the current record's "recipient" value
 * 
 * @package    userCache
 * @subpackage model
 * @author     Wojtek Sznapka
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('subject', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('recipient_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as recipient', array(
             'local' => 'recipient_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}