<?php

/**
 * sfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    userCache
 * @subpackage model
 * @author     Wojtek Sznapka
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardRememberKey extends PluginsfGuardRememberKey
{
}
